## Table Extraction - Extract Table from Websites

In [ ]:
import pandas as pd

In [9]:
url = 'https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes_(seasons_1%E2%80%9320)'
simpsons = pd.read_html(url)

In [10]:
len(simpsons)

24

In [11]:
simpsons[1]

,No. overall,No. in season,Title,Directed by,Written by,Original air date,Prod. code,U.S. viewers (millions)
0,1,1,"""Simpsons Roasting on an Open Fire""",David Silverman,Mimi Pond,"December 17, 1989",7G08,26.7[46]
1,2,2,"""Bart the Genius""",David Silverman,Jon Vitti,"January 14, 1990",7G02,24.5[46]
2,3,3,"""Homer's Odyssey""",Wes Archer,Jay Kogen & Wallace Wolodarsky,"January 21, 1990",7G03,27.5[47]
3,4,4,"""There's No Disgrace Like Home""",Gregg Vanzo & Kent Butterworth,Al Jean & Mike Reiss,"January 28, 1990",7G04,20.2[48]
4,5,5,"""Bart the General""",David Silverman,John Swartzwelder,"February 4, 1990",7G05,27.1[49]
5,6,6,"""Moaning Lisa""",Wes Archer,Al Jean & Mike Reiss,"February 11, 1990",7G06,27.4[50]
6,7,7,"""The Call of the Simpsons""",Wes Archer,John Swartzwelder,"February 18, 1990",7G09,27.6[51]
7,8,8,"""The Telltale Head""",Rich Moore,"Al Jean, Mike Reiss, Sam Simon & Matt Groening","February 25, 1990",7G07,28.0[52]
8,9,9,"""Life on the Fast Lane""",David Silverman,John Swartzwelder,"March 18, 1990",7G11,33.5[53]
9,10,10,"""Homer's Night Out""",Rich Moore,Jon Vitti,"March 25, 1990",7G10,30.3[54]
10,11,11,"""The Crepes of Wrath""",Wes Archer & Milton Gray,"George Meyer, Sam Simon, John Swartzwelder & J...","April 15, 1990",7G13,31.2[55]
11,12,12,"""Krusty Gets Busted""",Brad Bird,Jay Kogen & Wallace Wolodarsky,"April 29, 1990",7G12,30.4[56]
12,13,13,"""Some Enchanted Evening""",David Silverman & Kent Butterworth,Matt Groening & Sam Simon,"May 13, 1990",7G01,27.1[57]

### Read a .csv from a URL with Pandas
#### Target website: https://www.football-data.co.uk/data.php

In [15]:
# Reading 1 csv file from the website

df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [16]:
# Rename columns

df_premier21.rename(columns = {'FTHG': 'home_goals',
                               'FTAG': 'away_goals'}, inplace = True)
df_premier21.head(3)

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12

### Table Extraction:
##### Extract Tables from PDF

In [22]:
!python -m pip install camelot-py
!python -m pip install ghostscript
!python -m pip install tk

Collecting camelot-py
  Downloading camelot_py-0.11.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: chardet>=3.0.4 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (4.0.0)
Requirement already satisfied: click>=6.7 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (8.0.4)
Requirement already satisfied: numpy>=1.13.3 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (1.24.3)
Requirement already satisfied: openpyxl>=2.5.8 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (3.0.10)
Requirement already satisfied: pandas>=0.23.4 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (1.5.3)
Collecting pdfminer.six>=20200726 (from camelot-py)
  Obtaining dependency information for pdfminer.six>=20200726 from https://files.pythonhosted.org/packages/eb/9c/e46fe7502b32d7db6af6e36a9105abb93301fa1ec475b5ddcba8b35ae23a/pdfminer.six-20231228-py3-none-any.whl.metadata
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Collecting pypdf>=3.0.0 (from camelot-py)
  Obtaining dependency information for pypdf>=3.0.0 from https://files.pythonhosted.org/packages/29/10/055b649e914ad8c5d07113c22805014988825abbeff007b0e89255b481fa/pypdf-3.17.4-py3-none-any.whl.metadata
  Downloading pypdf-3.17.4-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: tabulate>=0.8.9 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from camelot-py) (0.8.10)
Requirement already satisfied: et_xmlfile in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from openpyxl>=2.5.8->camelot-py) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from pandas>=0.23.4->camelot-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from pandas>=0.23.4->camelot-py) (2022.7)
Requirement already satisfied: charset-normalizer>=2.0.0 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from pdfminer.six>=20200726->camelot-py) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from pdfminer.six>=20200726->camelot-py) (41.0.3)
Requirement already satisfied: cffi>=1.12 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py) (1.15.1)
Requirement already satisfied: six>=1.5 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas>=0.23.4->camelot-py) (1.16.0)
Requirement already satisfied: pycparser in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py) (2.21)
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 1.5 MB/s eta 0:00:0000:0100:01
Downloading pypdf-3.17.4-py3-none-any.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 1.0 MB/s eta 0:00:0000:0100:01
Installing collected packages: pypdf, pdfminer.six, camelot-py
Successfully installed camelot-py-0.11.0 pdfminer.six-20231228 pypdf-3.17.4
Collecting ghostscript
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools>=38.6.0 in /Users/rhumagai/anaconda3/lib/python3.11/site-packages (from ghostscript) (68.0.0)
Installing collected packages: ghostscript
Successfully installed ghostscript-0.7
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
Installing collected packages: tk
Successfully installed tk-0.1.0

In [ ]:
import camelot

camelot.read_pdf('foo.pdf', pages = '1', )